import mongoose from 'mongoose';
import slugify from 'slugify';
import { inferCategoryIcon } from '../utils/categoryIcon.js';

/**
 * CATEGORY MODEL - Business-scoped product/service categories
 * Created by dukandar for their listings (products/services)
 * Examples: For Kirana -> Grocery, Dairy, Snacks; For Restaurant -> Fast Food, Chinese, Beverages
 * Each business has its own categories
 */

const categorySchema = new mongoose.Schema(
  {
    business: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Business',
      required: [true, 'Business reference is required'],
    },
    name: {
      type: String,
      required: [true, 'Category name is required'],
      trim: true,
      maxlength: [100, 'Category name cannot exceed 100 characters'],
    },
    slug: {
      type: String,
      lowercase: true,
      trim: true,
      // Not required here since it's auto-generated by pre-save hook
    },
    description: {
      type: String,
      maxlength: [500, 'Description cannot exceed 500 characters'],
    },
    image: {
      type: String, // Cloudinary URL
    },
    icon: {
      type: String, // Emoji (server-inferred from name)
      trim: true,
      maxlength: [32, 'Icon cannot exceed 32 characters'],
    },
    isActive: {
      type: Boolean,
      default: true,
    },
    order: {
      type: Number,
      default: 0, // For sorting categories
    },
  },
  {
    timestamps: true,
  }
);

// Auto-infer icon from name when not provided
categorySchema.pre('validate', function (next) {
  if (!this.icon) {
    this.icon = inferCategoryIcon(this.name);
  }
  next();
});

// Compound unique index: slug must be unique within a business
categorySchema.index({ business: 1, slug: 1 }, { unique: true });
// Index for querying active categories by business
categorySchema.index({ business: 1, isActive: 1, order: 1 });

// Auto-generate slug from name (unique per business)
categorySchema.pre('save', async function (next) {
  if (!this.isModified('name') && this.slug) {
    return next();
  }

  try {
    let baseSlug = slugify(this.name, {
      lower: true,
      strict: true,
      remove: /[*+~.()'"!:@]/g,
    });

    let slug = baseSlug;
    let counter = 1;

    // Ensure uniqueness within the business
    while (await mongoose.model('Category').findOne({ 
      business: this.business, 
      slug, 
      _id: { $ne: this._id } 
    })) {
      slug = `${baseSlug}-${counter}`;
      counter++;
    }

    this.slug = slug;
    next();
  } catch (error) {
    next(error);
  }
});

const Category = mongoose.model('Category', categorySchema);

export default Category;
